CREATE TABLE EMPLOYEE4
(EID INT,
ENAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY DECIMAL(8,2),
JOININGDATE DATE,
CITY VARCHAR(50)
)

INSERT INTO EMPLOYEE4 VALUES(101,'RAHUL','ADMIN',56000,'1-JAN-90','RAJKOT'),
(102,'HARDIK','IT',18000,'25-SEP-90','AHMEDABAD'),
(103,'BHAVIN','HR',25000,'14-MAY-91','BARODA'),
(104,'BHOOMI','ADMIN',39000,'8-FEB-91','RAJKOT'),
(105,'ROHIT','IT',17000,'23-JAN-90','JAMNAGAR'),
(106,'PRIYA','IT',9000,'19-OCT-90','AHMEDABAD'),
(107,'NEHA','HR',34000,'25-DEC-91','RAJKOT')

select * from EMPLOYEE4
--1
SELECT MAX(SALARY) MAXIMUM, MIN(SALARY) MINIMUM, SUM(SALARY) Total_Sal, AVG(SALARY) Average_Sal FROM EMPLOYEE4
--2
SELECT COUNT(EID) FROM EMPLOYEE4
--3
SELECT MAX(SALARY) MAXIMUM FROM EMPLOYEE4 WHERE DEPARTMENT = 'IT'
--4
SELECT COUNT(DISTINCT CITY) FROM EMPLOYEE4
--5
SELECT CITY,COUNT(EID) FROM EMPLOYEE4 GROUP BY CITY
--6
SELECT CITY,COUNT(EName) FROM EMPLOYEE4 GROUP BY CITY
--7
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE4
GROUP BY DEPARTMENT;
--8
SELECT DEPARTMENT, AVG(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE4
GROUP BY DEPARTMENT
--9
SELECT MIN(SALARY) AS MINIMUM_SALARY
FROM EMPLOYEE4
WHERE CITY = 'AHMEDABAD'
--10
SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE4
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>50000 
--11
select COUNT(EID) FROM EMPLOYEE4
WHERE CITY='RAJKOT'
--12
SELECT MAX(SALARY)-MIN(SALARY) DIFFERENCE FROM EMPLOYEE4
--13
SELECT COUNT(EID) FROM EMPLOYEE4
WHERE JOININGDATE < '01-JAN-1991'
--14
SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEE4
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>35000
ORDER BY SUM(SALARY)
--15
SELECT DEPARTMENT,COUNT(EID) FROM EMPLOYEE4
GROUP BY DEPARTMENT
HAVING COUNT(EID)>2













